// Package menu is the config menu: the catalog the dashboard offers
// (`GET /catalog`), the validator for a selection, and the renderer that
// turns a selection into the fragment the build pipeline consumes
// (docs/workstreams/12-nix-config-pipeline.md "The menu"). The api calls
// it; hostd never sees a selection, only the rendered fragment.
//
// A rendered fragment is an ordinary fragment under the contract in
// nix/guest/contract.nix: each entry's `hm` snippet becomes one module in
// `imports`, and its `nixos` snippet one `repose.system` entry, which the
// composer checks against the allowlist again at evaluation. The header
// carries the selection as JSON so a menu-managed fragment round-trips.
package menu

import (
	"bytes"
	_ "embed"
	"encoding/json"
	"fmt"
	"regexp"
	"sort"
	"strings"
	"text/template"

	"gopkg.in/yaml.v3"
)

//go:embed catalog.yaml
var catalogYAML []byte

// Header is the first line of every generated fragment; the api treats a
// fragment that lacks it as hand-written (menu off, "takeover").
const Header = "# generated by repose from your menu selection; edit with repose config edit to take over"

// selectionPrefix introduces the JSON line that makes the fragment
// round-trip.
const selectionPrefix = "# repose-menu: "

// Kinds a catalog entry may have.
var Kinds = []string{"service", "package", "agent", "runtime"}

// Entry is one catalog item.
type Entry struct {
	ID          string   `yaml:"id" json:"id"`
	Label       string   `yaml:"label" json:"label"`
	Group       string   `yaml:"group" json:"group"`
	Kind        string   `yaml:"kind" json:"kind"`
	Description string   `yaml:"description" json:"description"`
	HM          string   `yaml:"hm,omitempty" json:"-"`
	NixOS       string   `yaml:"nixos,omitempty" json:"-"`
	Options     []Option `yaml:"options,omitempty" json:"options,omitempty"`
}

// Option is a per-entry choice; today every option is an enum.
type Option struct {
	ID      string   `yaml:"id" json:"id"`
	Type    string   `yaml:"type" json:"type"`
	Values  []string `yaml:"values" json:"values"`
	Default string   `yaml:"default" json:"default"`
}

// Item is one element of a MenuSelection (docs/interfaces/api.md):
// `[{id, options: {name: value}}]`.
type Item struct {
	ID      string            `json:"id"`
	Options map[string]string `json:"options,omitempty"`
}

// Selection is what PUT /config carries as `menu`.
type Selection []Item

// Error is a validation failure the api returns as `invalid` with the
// message (docs/interfaces/api.md "Errors").
type Error struct {
	Code    string
	Message string
}

func (e *Error) Error() string { return e.Code + ": " + e.Message }

func invalid(format string, a ...any) *Error {
	return &Error{Code: "invalid", Message: fmt.Sprintf(format, a...)}
}

// Catalog is the loaded, validated catalog.
type Catalog struct {
	Entries []Entry
	byID    map[string]*Entry
}

var idRe = regexp.MustCompile(`^[a-z][a-z0-9-]{0,39}$`)

var funcs = template.FuncMap{
	"nodots": func(s string) string { return strings.ReplaceAll(s, ".", "") },
}

// Load parses the embedded catalog and checks it: unique well-formed ids,
// known kinds, snippets that are valid templates whose option references
// exist, defaults that are among the values, and every `nixos` snippet
// inside the allowlist (lint.go).
func Load() (*Catalog, error) {
	return Parse(catalogYAML)
}

// Parse loads a catalog from YAML; the tests feed it bad entries.
func Parse(b []byte) (*Catalog, error) {
	var entries []Entry
	if err := yaml.Unmarshal(b, &entries); err != nil {
		return nil, fmt.Errorf("catalog: %w", err)
	}
	c := &Catalog{Entries: entries, byID: map[string]*Entry{}}
	for i := range c.Entries {
		e := &c.Entries[i]
		if !idRe.MatchString(e.ID) {
			return nil, fmt.Errorf("catalog: entry %d: id %q is not [a-z][a-z0-9-]*", i, e.ID)
		}
		if _, dup := c.byID[e.ID]; dup {
			return nil, fmt.Errorf("catalog: duplicate id %q", e.ID)
		}
		if e.Label == "" || e.Group == "" || e.Description == "" {
			return nil, fmt.Errorf("catalog: %s: label, group and description are required", e.ID)
		}
		if !contains(Kinds, e.Kind) {
			return nil, fmt.Errorf("catalog: %s: kind %q is not one of %v", e.ID, e.Kind, Kinds)
		}
		if e.HM == "" && e.NixOS == "" {
			return nil, fmt.Errorf("catalog: %s: needs an hm or a nixos snippet", e.ID)
		}
		if e.Kind == "service" && e.NixOS == "" {
			return nil, fmt.Errorf("catalog: %s: a service needs a nixos snippet", e.ID)
		}
		if e.Kind != "service" && e.NixOS != "" {
			return nil, fmt.Errorf("catalog: %s: only a service may carry a nixos snippet", e.ID)
		}
		seen := map[string]bool{}
		for _, o := range e.Options {
			if !idRe.MatchString(o.ID) || seen[o.ID] {
				return nil, fmt.Errorf("catalog: %s: option id %q invalid or duplicate", e.ID, o.ID)
			}
			seen[o.ID] = true
			if o.Type != "enum" {
				return nil, fmt.Errorf("catalog: %s: option %s: type %q is not enum", e.ID, o.ID, o.Type)
			}
			if len(o.Values) == 0 || !contains(o.Values, o.Default) {
				return nil, fmt.Errorf("catalog: %s: option %s: default %q is not among values %v", e.ID, o.ID, o.Default, o.Values)
			}
		}
		// Every template renders with the defaults, and references only
		// declared options (a missing key is an error under missingkey).
		if _, err := e.render(e.defaults()); err != nil {
			return nil, fmt.Errorf("catalog: %s: %w", e.ID, err)
		}
		if err := LintSnippet(e.NixOS); err != nil {
			return nil, fmt.Errorf("catalog: %s: nixos snippet: %w", e.ID, err)
		}
		c.byID[e.ID] = e
	}
	return c, nil
}

func contains(xs []string, x string) bool {
	for _, y := range xs {
		if y == x {
			return true
		}
	}
	return false
}

// Public is the `GET /catalog` shape: every entry without its snippets.
func (c *Catalog) Public() []Entry {
	out := make([]Entry, len(c.Entries))
	for i, e := range c.Entries {
		e.HM, e.NixOS = "", ""
		out[i] = e
	}
	return out
}

// Entry looks an id up.
func (c *Catalog) Entry(id string) (*Entry, bool) {
	e, ok := c.byID[id]
	return e, ok
}

func (e *Entry) defaults() map[string]string {
	m := map[string]string{}
	for _, o := range e.Options {
		m[o.ID] = o.Default
	}
	return m
}

type rendered struct {
	hm, nixos string
}

func (e *Entry) render(opts map[string]string) (rendered, error) {
	var r rendered
	var err error
	if r.hm, err = renderTemplate(e.ID+".hm", e.HM, opts); err != nil {
		return r, err
	}
	if r.nixos, err = renderTemplate(e.ID+".nixos", e.NixOS, opts); err != nil {
		return r, err
	}
	return r, nil
}

func renderTemplate(name, text string, opts map[string]string) (string, error) {
	if text == "" {
		return "", nil
	}
	t, err := template.New(name).Funcs(funcs).Option("missingkey=error").Parse(text)
	if err != nil {
		return "", err
	}
	var b bytes.Buffer
	if err := t.Execute(&b, opts); err != nil {
		return "", err
	}
	return b.String(), nil
}

// Validate checks a selection against the catalog: known ids, no
// duplicates, known options with allowed values. Unknown ids come back as
// `invalid` naming the id (docs/interfaces/api.md).
func (c *Catalog) Validate(sel Selection) error {
	if len(sel) == 0 {
		return invalid("menu selection is empty")
	}
	seen := map[string]bool{}
	for _, it := range sel {
		e, ok := c.byID[it.ID]
		if !ok {
			return invalid("unknown catalog id %q", it.ID)
		}
		if seen[it.ID] {
			return invalid("catalog id %q selected twice", it.ID)
		}
		seen[it.ID] = true
		for name, val := range it.Options {
			var opt *Option
			for i := range e.Options {
				if e.Options[i].ID == name {
					opt = &e.Options[i]
				}
			}
			if opt == nil {
				return invalid("%s has no option %q", it.ID, name)
			}
			if !contains(opt.Values, val) {
				return invalid("%s: option %s: %q is not one of %v", it.ID, name, val, opt.Values)
			}
		}
	}
	return nil
}

// Normalize returns the selection with every option filled from its
// default, sorted by catalog order, which is also how it is rendered.
func (c *Catalog) Normalize(sel Selection) (Selection, error) {
	if err := c.Validate(sel); err != nil {
		return nil, err
	}
	pos := map[string]int{}
	for i, e := range c.Entries {
		pos[e.ID] = i
	}
	out := make(Selection, 0, len(sel))
	for _, it := range sel {
		e := c.byID[it.ID]
		opts := e.defaults()
		for k, v := range it.Options {
			opts[k] = v
		}
		if len(opts) == 0 {
			opts = nil
		}
		out = append(out, Item{ID: it.ID, Options: opts})
	}
	sort.SliceStable(out, func(i, j int) bool { return pos[out[i].ID] < pos[out[j].ID] })
	return out, nil
}

// Render turns a selection into the generated fragment.
func (c *Catalog) Render(sel Selection) (string, error) {
	norm, err := c.Normalize(sel)
	if err != nil {
		return "", err
	}
	selJSON, err := json.Marshal(norm)
	if err != nil {
		return "", fmt.Errorf("menu: %w", err)
	}
	var b strings.Builder
	b.WriteString(Header + "\n")
	b.WriteString(selectionPrefix + string(selJSON) + "\n")
	b.WriteString("{ config, pkgs, lib, ... }:\n{\n  imports = [\n")
	for _, it := range norm {
		e := c.byID[it.ID]
		r, err := e.render(it.Options)
		if err != nil {
			return "", fmt.Errorf("menu: %s: %w", it.ID, err)
		}
		fmt.Fprintf(&b, "    # %s (%s): %s\n", e.ID, e.Group, describe(e, it.Options))
		b.WriteString("    {\n")
		if r.hm != "" {
			b.WriteString(indent(r.hm, "      "))
		}
		if r.nixos != "" {
			b.WriteString("      repose.system = [\n        {\n")
			b.WriteString(indent(r.nixos, "          "))
			b.WriteString("        }\n      ];\n")
		}
		b.WriteString("    }\n")
	}
	b.WriteString("  ];\n}\n")
	return b.String(), nil
}

func describe(e *Entry, opts map[string]string) string {
	if len(opts) == 0 {
		return e.Label
	}
	keys := make([]string, 0, len(opts))
	for k := range opts {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	parts := make([]string, 0, len(keys))
	for _, k := range keys {
		parts = append(parts, k+" "+opts[k])
	}
	return e.Label + " " + strings.Join(parts, ", ")
}

func indent(s, prefix string) string {
	var b strings.Builder
	for _, l := range strings.Split(strings.TrimRight(s, "\n"), "\n") {
		if l == "" {
			b.WriteString("\n")
			continue
		}
		b.WriteString(prefix + l + "\n")
	}
	return b.String()
}

// IsGenerated reports whether a fragment was produced by Render and not
// edited past its header (the api's menu-versus-fragment switch).
func IsGenerated(fragment string) bool {
	return strings.HasPrefix(fragment, Header+"\n"+selectionPrefix)
}

// ParseGenerated recovers the selection from a generated fragment.
func ParseGenerated(fragment string) (Selection, bool) {
	if !IsGenerated(fragment) {
		return nil, false
	}
	rest := strings.TrimPrefix(fragment, Header+"\n"+selectionPrefix)
	line := rest
	if i := strings.IndexByte(rest, '\n'); i >= 0 {
		line = rest[:i]
	}
	var sel Selection
	if err := json.Unmarshal([]byte(line), &sel); err != nil {
		return nil, false
	}
	return sel, true
}
