// Package menu is the config menu: the catalog the dashboard offers
// (`GET /catalog`), the validator for a selection, and the renderer that
// turns a selection into the fragment the build pipeline consumes
// (docs/workstreams/12-nix-config-pipeline.md "The menu"). The api calls
// it; hostd never sees a selection, only the rendered fragment.
//
// A rendered fragment is an ordinary fragment under the contract in
// nix/guest/contract.nix: each entry's `hm` snippet becomes one module in
// `imports`, and its `nixos` snippet one `repose.system` entry, which the
// composer checks against the allowlist again at evaluation. The header
// carries the selection as JSON so a menu-managed fragment round-trips.
package menu

import (
	"bytes"
	_ "embed"
	"encoding/json"
	"fmt"
	"regexp"
	"sort"
	"strings"
	"text/template"

	"gopkg.in/yaml.v3"
)

//go:embed catalog.yaml
var catalogYAML []byte

// Header is the first line of every generated fragment; the api treats a
// fragment that lacks it as hand-written (menu off, "takeover").
const Header = "# generated by repose from your menu selection; edit with repose config edit to take over"

// selectionPrefix introduces the JSON line that makes the fragment
// round-trip.
const selectionPrefix = "# repose-menu: "

// Kinds a catalog entry may have.
var Kinds = []string{"service", "package", "agent", "runtime"}

// Entry is one catalog item.
type Entry struct {
	ID          string   `yaml:"id" json:"id"`
	Label       string   `yaml:"label" json:"label"`
	Group       string   `yaml:"group" json:"group"`
	Kind        string   `yaml:"kind" json:"kind"`
	Description string   `yaml:"description" json:"description"`
	HM          string   `yaml:"hm,omitempty" json:"-"`
	NixOS       string   `yaml:"nixos,omitempty" json:"-"`
	Options     []Option `yaml:"options,omitempty" json:"options,omitempty"`
}

// Option is a per-entry choice; today every option is an enum.
type Option struct {
	ID      string   `yaml:"id" json:"id"`
	Type    string   `yaml:"type" json:"type"`
	Values  []string `yaml:"values" json:"values"`
	Default string   `yaml:"default" json:"default"`
}

// Item is one element of a MenuSelection (docs/interfaces/api.md): a
// catalog entry `{id, options?: {name: value}}`, or any nixpkgs package by
// attribute path `{package: "python312Packages.black"}` (DECISIONS I-220).
// An item carries exactly one of ID and Package.
type Item struct {
	ID      string            `json:"id,omitempty"`
	Options map[string]string `json:"options,omitempty"`
	Package string            `json:"package,omitempty"`
}

// Selection is what PUT /config carries as `menu`.
type Selection []Item

// Error is a validation failure the api returns as `invalid` with the
// message (docs/interfaces/api.md "Errors").
type Error struct {
	Code    string
	Message string
}

func (e *Error) Error() string { return e.Code + ": " + e.Message }

func invalid(format string, a ...any) *Error {
	return &Error{Code: "invalid", Message: fmt.Sprintf(format, a...)}
}

// Catalog is the loaded, validated catalog.
type Catalog struct {
	Entries []Entry
	byID    map[string]*Entry
}

var idRe = regexp.MustCompile(`^[a-z][a-z0-9-]{0,39}$`)

// MaxPackageLen caps a package attribute path.
const MaxPackageLen = 200

// packageRe is a nixpkgs attribute path: dot-separated Nix identifiers
// (letters, digits, `_`, `-`, `+`; not starting with a digit, `-` or `+`).
// Nothing that can end a Nix string or start an interpolation (`"`, `\`,
// `$`) matches, and neither does whitespace, so a name is rendered inside
// a Nix string literal and can only ever be looked up, never evaluated.
var packageRe = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_+-]*(\.[A-Za-z_][A-Za-z0-9_+-]*)*$`)

// ValidPackage reports whether name is an acceptable nixpkgs attribute
// path for a `{package}` item.
func ValidPackage(name string) bool {
	return len(name) <= MaxPackageLen && packageRe.MatchString(name)
}

// PackageNotFound is the message a missing package fails the build with,
// through the fragment's own `throw` (hostd reports it as the eval_failed
// summary, docs/interfaces/nix-build-contract.md "What the user reads").
func PackageNotFound(name string) string {
	return `nixpkgs has no package "` + name + `"; search https://search.nixos.org/packages`
}

var funcs = template.FuncMap{
	"nodots": func(s string) string { return strings.ReplaceAll(s, ".", "") },
}

// Load parses the embedded catalog and checks it: unique well-formed ids,
// known kinds, snippets that are valid templates whose option references
// exist, defaults that are among the values, and every `nixos` snippet
// inside the allowlist (lint.go).
func Load() (*Catalog, error) {
	return Parse(catalogYAML)
}

// Parse loads a catalog from YAML; the tests feed it bad entries.
func Parse(b []byte) (*Catalog, error) {
	var entries []Entry
	if err := yaml.Unmarshal(b, &entries); err != nil {
		return nil, fmt.Errorf("catalog: %w", err)
	}
	c := &Catalog{Entries: entries, byID: map[string]*Entry{}}
	for i := range c.Entries {
		e := &c.Entries[i]
		if !idRe.MatchString(e.ID) {
			return nil, fmt.Errorf("catalog: entry %d: id %q is not [a-z][a-z0-9-]*", i, e.ID)
		}
		if _, dup := c.byID[e.ID]; dup {
			return nil, fmt.Errorf("catalog: duplicate id %q", e.ID)
		}
		if e.Label == "" || e.Group == "" || e.Description == "" {
			return nil, fmt.Errorf("catalog: %s: label, group and description are required", e.ID)
		}
		if !contains(Kinds, e.Kind) {
			return nil, fmt.Errorf("catalog: %s: kind %q is not one of %v", e.ID, e.Kind, Kinds)
		}
		if e.HM == "" && e.NixOS == "" {
			return nil, fmt.Errorf("catalog: %s: needs an hm or a nixos snippet", e.ID)
		}
		if e.Kind == "service" && e.NixOS == "" {
			return nil, fmt.Errorf("catalog: %s: a service needs a nixos snippet", e.ID)
		}
		if e.Kind != "service" && e.NixOS != "" {
			return nil, fmt.Errorf("catalog: %s: only a service may carry a nixos snippet", e.ID)
		}
		seen := map[string]bool{}
		for _, o := range e.Options {
			if !idRe.MatchString(o.ID) || seen[o.ID] {
				return nil, fmt.Errorf("catalog: %s: option id %q invalid or duplicate", e.ID, o.ID)
			}
			seen[o.ID] = true
			if o.Type != "enum" {
				return nil, fmt.Errorf("catalog: %s: option %s: type %q is not enum", e.ID, o.ID, o.Type)
			}
			if len(o.Values) == 0 || !contains(o.Values, o.Default) {
				return nil, fmt.Errorf("catalog: %s: option %s: default %q is not among values %v", e.ID, o.ID, o.Default, o.Values)
			}
		}
		// Every template renders with the defaults, and references only
		// declared options (a missing key is an error under missingkey).
		if _, err := e.render(e.defaults()); err != nil {
			return nil, fmt.Errorf("catalog: %s: %w", e.ID, err)
		}
		if err := LintSnippet(e.NixOS); err != nil {
			return nil, fmt.Errorf("catalog: %s: nixos snippet: %w", e.ID, err)
		}
		c.byID[e.ID] = e
	}
	return c, nil
}

func contains(xs []string, x string) bool {
	for _, y := range xs {
		if y == x {
			return true
		}
	}
	return false
}

// Public is the `GET /catalog` shape: every entry without its snippets.
func (c *Catalog) Public() []Entry {
	out := make([]Entry, len(c.Entries))
	for i, e := range c.Entries {
		e.HM, e.NixOS = "", ""
		out[i] = e
	}
	return out
}

// Entry looks an id up.
func (c *Catalog) Entry(id string) (*Entry, bool) {
	e, ok := c.byID[id]
	return e, ok
}

func (e *Entry) defaults() map[string]string {
	m := map[string]string{}
	for _, o := range e.Options {
		m[o.ID] = o.Default
	}
	return m
}

type rendered struct {
	hm, nixos string
}

func (e *Entry) render(opts map[string]string) (rendered, error) {
	var r rendered
	var err error
	if r.hm, err = renderTemplate(e.ID+".hm", e.HM, opts); err != nil {
		return r, err
	}
	if r.nixos, err = renderTemplate(e.ID+".nixos", e.NixOS, opts); err != nil {
		return r, err
	}
	return r, nil
}

func renderTemplate(name, text string, opts map[string]string) (string, error) {
	if text == "" {
		return "", nil
	}
	t, err := template.New(name).Funcs(funcs).Option("missingkey=error").Parse(text)
	if err != nil {
		return "", err
	}
	var b bytes.Buffer
	if err := t.Execute(&b, opts); err != nil {
		return "", err
	}
	return b.String(), nil
}

// Validate checks a selection against the catalog: known ids, no
// duplicates, known options with allowed values. Unknown ids come back as
// `invalid` naming the id (docs/interfaces/api.md).
func (c *Catalog) Validate(sel Selection) error {
	seen := map[string]bool{}
	seenPkg := map[string]bool{}
	for _, it := range sel {
		if it.Package != "" {
			if it.ID != "" || len(it.Options) > 0 {
				return invalid("a menu item has either id (with options) or package, not both")
			}
			if !ValidPackage(it.Package) {
				return invalid("%q is not a nixpkgs attribute path (letters, digits, _ - + and dots, at most %d characters)", it.Package, MaxPackageLen)
			}
			if _, ok := c.byID[it.Package]; ok {
				return invalid("%q is a catalog id; select it as {\"id\": %q}", it.Package, it.Package)
			}
			if seenPkg[it.Package] {
				return invalid("package %q selected twice", it.Package)
			}
			seenPkg[it.Package] = true
			continue
		}
		if it.ID == "" {
			return invalid("a menu item needs an id or a package")
		}
		e, ok := c.byID[it.ID]
		if !ok {
			return invalid("unknown catalog id %q", it.ID)
		}
		if seen[it.ID] {
			return invalid("catalog id %q selected twice", it.ID)
		}
		seen[it.ID] = true
		for name, val := range it.Options {
			var opt *Option
			for i := range e.Options {
				if e.Options[i].ID == name {
					opt = &e.Options[i]
				}
			}
			if opt == nil {
				return invalid("%s has no option %q", it.ID, name)
			}
			if !contains(opt.Values, val) {
				return invalid("%s: option %s: %q is not one of %v", it.ID, name, val, opt.Values)
			}
		}
	}
	return nil
}

// Normalize returns the selection with every option filled from its
// default, sorted by catalog order with the packages after the catalog
// entries in name order, which is also how it is rendered.
func (c *Catalog) Normalize(sel Selection) (Selection, error) {
	if err := c.Validate(sel); err != nil {
		return nil, err
	}
	pos := map[string]int{}
	for i, e := range c.Entries {
		pos[e.ID] = i
	}
	out := make(Selection, 0, len(sel))
	var pkgs []string
	for _, it := range sel {
		if it.Package != "" {
			pkgs = append(pkgs, it.Package)
			continue
		}
		e := c.byID[it.ID]
		opts := e.defaults()
		for k, v := range it.Options {
			opts[k] = v
		}
		if len(opts) == 0 {
			opts = nil
		}
		out = append(out, Item{ID: it.ID, Options: opts})
	}
	sort.SliceStable(out, func(i, j int) bool { return pos[out[i].ID] < pos[out[j].ID] })
	sort.Strings(pkgs)
	for _, p := range pkgs {
		out = append(out, Item{Package: p})
	}
	return out, nil
}

// Render turns a selection into the generated fragment.
func (c *Catalog) Render(sel Selection) (string, error) {
	norm, err := c.Normalize(sel)
	if err != nil {
		return "", err
	}
	selJSON, err := json.Marshal(norm)
	if err != nil {
		return "", fmt.Errorf("menu: %w", err)
	}
	var pkgs []string
	for _, it := range norm {
		if it.Package != "" {
			pkgs = append(pkgs, it.Package)
		}
	}
	var b strings.Builder
	b.WriteString(Header + "\n")
	b.WriteString(selectionPrefix + string(selJSON) + "\n")
	b.WriteString("{ config, pkgs, lib, ... }:\n")
	if len(pkgs) > 0 {
		b.WriteString(nixpkgHelper)
	}
	b.WriteString("{\n  imports = [\n")
	for _, it := range norm {
		if it.Package != "" {
			continue
		}
		e := c.byID[it.ID]
		r, err := e.render(it.Options)
		if err != nil {
			return "", fmt.Errorf("menu: %s: %w", it.ID, err)
		}
		fmt.Fprintf(&b, "    # %s (%s): %s\n", e.ID, e.Group, describe(e, it.Options))
		b.WriteString("    {\n")
		if r.hm != "" {
			b.WriteString(indent(r.hm, "      "))
		}
		if r.nixos != "" {
			b.WriteString("      repose.system = [\n        {\n")
			b.WriteString(indent(r.nixos, "          "))
			b.WriteString("        }\n      ];\n")
		}
		b.WriteString("    }\n")
	}
	if len(pkgs) > 0 {
		fmt.Fprintf(&b, "    # extra packages from nixpkgs: %s\n", strings.Join(pkgs, ", "))
		b.WriteString("    {\n      home.packages = [\n")
		for _, p := range pkgs {
			lit, err := nixPath(p)
			if err != nil {
				return "", err
			}
			fmt.Fprintf(&b, "        (nixpkg %s)\n", lit)
		}
		b.WriteString("      ];\n    }\n")
	}
	b.WriteString("  ];\n}\n")
	return b.String(), nil
}

// nixpkgHelper looks a package up by attribute path, so a name the user
// typed is only ever a string handed to lib.attrByPath, and a missing one
// fails the build with PackageNotFound's message rather than Nix's
// "attribute missing" pointing at a line the user never wrote. An unfree
// package outside the allowlist still fails with nixpkgs' own refusal when
// home-manager evaluates it.
const nixpkgHelper = `let
  # Any nixpkgs package by attribute path (repose config add, DECISIONS I-220).
  nixpkg = path:
    let
      name = lib.concatStringsSep "." path;
      p = lib.attrByPath path null pkgs;
    in
    if p == null then throw "nixpkgs has no package \"${name}\"; search https://search.nixos.org/packages"
    else if lib.isDerivation p then p
    else throw "nixpkgs attribute \"${name}\" is not a package; search https://search.nixos.org/packages";
in
`

// nixPath renders an attribute path as a Nix list of string literals:
// "python312Packages.black" -> [ "python312Packages" "black" ]. ValidPackage
// already excludes every character that is special inside a Nix string;
// the check is repeated here so no caller can render an unchecked name.
func nixPath(name string) (string, error) {
	if !ValidPackage(name) {
		return "", invalid("%q is not a nixpkgs attribute path", name)
	}
	parts := strings.Split(name, ".")
	for i, p := range parts {
		parts[i] = `"` + p + `"`
	}
	return "[ " + strings.Join(parts, " ") + " ]", nil
}

func describe(e *Entry, opts map[string]string) string {
	if len(opts) == 0 {
		return e.Label
	}
	keys := make([]string, 0, len(opts))
	for k := range opts {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	parts := make([]string, 0, len(keys))
	for _, k := range keys {
		parts = append(parts, k+" "+opts[k])
	}
	return e.Label + " " + strings.Join(parts, ", ")
}

func indent(s, prefix string) string {
	var b strings.Builder
	for _, l := range strings.Split(strings.TrimRight(s, "\n"), "\n") {
		if l == "" {
			b.WriteString("\n")
			continue
		}
		b.WriteString(prefix + l + "\n")
	}
	return b.String()
}

// IsGenerated reports whether a fragment was produced by Render and not
// edited past its header (the api's menu-versus-fragment switch).
func IsGenerated(fragment string) bool {
	return strings.HasPrefix(fragment, Header+"\n"+selectionPrefix)
}

// ParseGenerated recovers the selection from a generated fragment.
func ParseGenerated(fragment string) (Selection, bool) {
	if !IsGenerated(fragment) {
		return nil, false
	}
	rest := strings.TrimPrefix(fragment, Header+"\n"+selectionPrefix)
	line := rest
	if i := strings.IndexByte(rest, '\n'); i >= 0 {
		line = rest[:i]
	}
	var sel Selection
	if err := json.Unmarshal([]byte(line), &sel); err != nil {
		return nil, false
	}
	return sel, true
}
