# generated by repose from your menu selection; edit with repose config edit to take over
# repose-menu: [{"package":"gcc"},{"package":"no-such-package-repose"}]
{ config, pkgs, lib, ... }:
let
  # Any nixpkgs package by attribute path (repose config add, DECISIONS I-220).
  nixpkg = path:
    let
      name = lib.concatStringsSep "." path;
      p = lib.attrByPath path null pkgs;
    in
    if p == null then throw "nixpkgs has no package \"${name}\"; search https://search.nixos.org/packages"
    else if lib.isDerivation p then p
    else throw "nixpkgs attribute \"${name}\" is not a package; search https://search.nixos.org/packages";
in
{
  imports = [
    # extra packages from nixpkgs: gcc, no-such-package-repose
    {
      home.packages = [
        (nixpkg [ "gcc" ])
        (nixpkg [ "no-such-package-repose" ])
      ];
    }
  ];
}
