# generated by repose from your menu selection; edit with repose config edit to take over
# repose-menu: [{"id":"bun"},{"id":"postgresql","options":{"version":"16"}}]
{ config, pkgs, lib, ... }:
{
  imports = [
    # bun (runtimes)
    {
      home.packages = [ pkgs.bun ];
    }
    # postgresql (databases): PostgreSQL 16
    {
      home.packages = [ pkgs.postgresql_16 ];
      repose.system = [
        {
          services.postgresql = {
            enable = true;
            package = pkgs.postgresql_16;
            dataDir = "/home/dev/.local/share/postgres/16";
            ensureDatabases = [ "dev" ];
            ensureUsers = [ { name = "dev"; ensureClauses.superuser = true; } ];
            authentication = "local all all trust\nhost all all 127.0.0.1/32 trust\nhost all all ::1/128 trust\n";
          };
        }
      ];
    }
  ];
}
