package cli

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"golang.org/x/crypto/ssh"

	"github.com/heracraft/repose/internal/ca/sshca"
	"github.com/heracraft/repose/internal/ca/testca"
	fakeapi "github.com/heracraft/repose/internal/fakes/api"
)

func withHome(t *testing.T) string {
	t.Helper()
	home := t.TempDir()
	old := os.Getenv("HOME")
	_ = os.Setenv("HOME", home)
	t.Cleanup(func() { _ = os.Setenv("HOME", old) })
	return home
}

func testProjects() []Project {
	return []Project{
		{ID: "p1", Slug: "todo-app"},
		{ID: "p2", Slug: "blog"},
	}
}

func TestRenderSSHConfigGolden(t *testing.T) {
	got := renderSSHConfig(testProjects(), "heracraft")
	want := `# Generated by repose; edits here are overwritten on the next ` + "`repose run`" + `.
Host blog.repose
  HostName ssh.repose.herakraft.co
  User blog.heracraft
  CertificateFile ~/.ssh/repose/id_ed25519-cert.pub
  IdentityFile ~/.ssh/id_ed25519
  UserKnownHostsFile ~/.ssh/repose/known_hosts
  ForwardAgent yes
  IdentitiesOnly yes
  ServerAliveInterval 30
Host todo-app.repose
  HostName ssh.repose.herakraft.co
  User todo-app.heracraft
  CertificateFile ~/.ssh/repose/id_ed25519-cert.pub
  IdentityFile ~/.ssh/id_ed25519
  UserKnownHostsFile ~/.ssh/repose/known_hosts
  ForwardAgent yes
  IdentitiesOnly yes
  ServerAliveInterval 30
`
	if got != want {
		t.Fatalf("renderSSHConfig mismatch:\ngot:\n%s\nwant:\n%s", got, want)
	}
}

func TestEnsureIncludeLineOnceAndFirst(t *testing.T) {
	home := withHome(t)
	path := filepath.Join(home, ".ssh", "config")
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		t.Fatal(err)
	}
	preexisting := "Host example.com\n  User bob\n"
	if err := os.WriteFile(path, []byte(preexisting), 0o600); err != nil {
		t.Fatal(err)
	}

	if err := ensureIncludeLine(path); err != nil {
		t.Fatal(err)
	}
	b1, _ := os.ReadFile(path)
	lines := strings.Split(string(b1), "\n")
	if lines[0] != includeComment || lines[1] != includeLine {
		t.Fatalf("include not first two lines: %q", string(b1))
	}
	if !strings.Contains(string(b1), preexisting) {
		t.Fatalf("preexisting content lost: %q", string(b1))
	}

	// Running again must not duplicate or otherwise change anything.
	if err := ensureIncludeLine(path); err != nil {
		t.Fatal(err)
	}
	b2, _ := os.ReadFile(path)
	if string(b1) != string(b2) {
		t.Fatalf("second run changed the file:\nfirst:\n%s\nsecond:\n%s", b1, b2)
	}
	if strings.Count(string(b2), includeLine) != 1 {
		t.Fatalf("include line duplicated: %q", string(b2))
	}
}

func TestCertUsableFor(t *testing.T) {
	ca, err := testca.New()
	if err != nil {
		t.Fatal(err)
	}
	_, pub, err := sshca.GenerateHostKey("test")
	if err != nil {
		t.Fatal(err)
	}
	now := time.Now()
	cert, err := ca.SignUserCert(pub, "u:handle", []string{"p1", "p2"}, time.Hour)
	if err != nil {
		t.Fatal(err)
	}

	if !certUsableFor(cert, []string{"p1", "p2"}, now, certReuseMargin) {
		t.Fatal("should be usable: covers both ids, plenty of validity")
	}
	if certUsableFor(cert, []string{"p1", "p3"}, now, certReuseMargin) {
		t.Fatal("should not be usable: does not cover p3")
	}
	if certUsableFor(cert, []string{"p1"}, now.Add(50*time.Minute), certReuseMargin) {
		t.Fatal("should not be usable: less than the 30m margin remains")
	}
	if certUsableFor(nil, []string{"p1"}, now, certReuseMargin) {
		t.Fatal("nil cert is never usable")
	}
}

func TestEnsureCertReusesValidCertificate(t *testing.T) {
	home := withHome(t)
	sd := filepath.Join(home, ".ssh", "repose")
	if err := os.MkdirAll(sd, 0o700); err != nil {
		t.Fatal(err)
	}

	// Plant an identity key and a certificate that already covers both
	// projects with plenty of validity left.
	if _, err := ensureIdentityKey(); err != nil {
		t.Fatal(err)
	}
	pubBytes, err := os.ReadFile(filepath.Join(home, ".ssh", "id_ed25519.pub"))
	if err != nil {
		t.Fatal(err)
	}
	pub, _, _, _, err := ssh.ParseAuthorizedKey(pubBytes)
	if err != nil {
		t.Fatal(err)
	}
	ca, err := testca.New()
	if err != nil {
		t.Fatal(err)
	}
	cert, err := ca.SignUserCert(pub, "u:handle", []string{"p1", "p2"}, sshca.UserCertTTL)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(sd, "id_ed25519-cert.pub"), []byte(sshca.Marshal(cert)+"\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	// A client that fails any request proves ensureCert made none.
	fake := fakeapi.New(fakeapi.Options{})
	defer fake.Close()
	fake.Fail("POST /certs", "internal")
	client := newClient(fake.URL()+"/v1", staticToken("tok"))

	certPath, err := ensureCert(context.Background(), client, certParams{Handle: "heracraft", Projects: testProjects()}, nil)
	if err != nil {
		t.Fatalf("ensureCert: %v", err)
	}
	if certPath != filepath.Join(sd, "id_ed25519-cert.pub") {
		t.Fatalf("unexpected cert path %q", certPath)
	}
	cfg, err := os.ReadFile(filepath.Join(sd, "config"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(cfg), "Host todo-app.repose") {
		t.Fatalf("ssh config missing project block: %s", cfg)
	}
}

func TestEnsureCertReissuesWhenProjectAdded(t *testing.T) {
	home := withHome(t)
	sd := filepath.Join(home, ".ssh", "repose")
	if err := os.MkdirAll(sd, 0o700); err != nil {
		t.Fatal(err)
	}
	if _, err := ensureIdentityKey(); err != nil {
		t.Fatal(err)
	}
	pubBytes, _ := os.ReadFile(filepath.Join(home, ".ssh", "id_ed25519.pub"))
	pub, _, _, _, _ := ssh.ParseAuthorizedKey(pubBytes)

	fake := fakeapi.New(fakeapi.Options{})
	defer fake.Close()
	client := newClient(fake.URL()+"/v1", staticToken("tok"))
	ctx := context.Background()
	p1, err := client.CreateProject(ctx, CreateProjectRequest{Name: "todo-app", Class: "large"})
	if err != nil {
		t.Fatal(err)
	}
	p2, err := client.CreateProject(ctx, CreateProjectRequest{Name: "blog", Class: "large"})
	if err != nil {
		t.Fatal(err)
	}
	projects := []Project{*p1, *p2}

	ca, err := testca.New()
	if err != nil {
		t.Fatal(err)
	}
	// Existing cert covers only p1; the account now also has p2, so
	// certUsableFor must say no and ensureCert must call the api again.
	old, err := ca.SignUserCert(pub, "u:handle", []string{p1.ID}, sshca.UserCertTTL)
	if err != nil {
		t.Fatal(err)
	}
	oldLine := sshca.Marshal(old) + "\n"
	if err := os.WriteFile(filepath.Join(sd, "id_ed25519-cert.pub"), []byte(oldLine), 0o600); err != nil {
		t.Fatal(err)
	}

	certPath, err := ensureCert(ctx, client, certParams{Handle: "heracraft", Projects: projects}, nil)
	if err != nil {
		t.Fatalf("ensureCert: %v", err)
	}
	newBytes, err := os.ReadFile(certPath)
	if err != nil {
		t.Fatal(err)
	}
	// The fake api's canned certificate text is not itself a parseable
	// certificate (docs/interfaces "Fake" makes no promise about its
	// bytes, only that IssueCert was called); what this test proves is
	// that certUsableFor's rejection of the stale cert drove ensureCert
	// to call the api again and overwrite the file, not reuse it.
	if string(newBytes) == oldLine {
		t.Fatal("ensureCert reused a certificate that does not cover the new project")
	}
}
