// Package nixmenu is the catalog behind GET /catalog and the renderer that
// turns a menu selection into a home-manager fragment (docs/features/
// config.md "Menu versus fragment"). Workstream 12 owns the catalog
// contents and format; this package is the api's view of it: package and
// program entries render into `home.packages` and `programs.*` lines of
// one generated fragment.
package nixmenu

import (
	"errors"
	"fmt"
	"sort"
	"strings"
)

// Item is one catalog entry as GET /catalog returns it.
type Item struct {
	ID          string   `json:"id"`
	Label       string   `json:"label"`
	Group       string   `json:"group"`
	Description string   `json:"description"`
	Kind        string   `json:"kind"`
	Options     []Option `json:"options,omitempty"`
	hm          func(opts map[string]string) string
}

// Option is a per-item choice.
type Option struct {
	ID      string   `json:"id"`
	Values  []string `json:"values"`
	Default string   `json:"default"`
}

// Selection is what PUT /config {menu} carries: `[{id, options}]`.
type Selection []Selected

// Selected is one chosen item.
type Selected struct {
	ID      string            `json:"id"`
	Options map[string]string `json:"options,omitempty"`
}

// Header is the first line of every generated fragment.
const Header = "# generated by repose from your menu selection; edit with repose config edit to take over"

// ErrUnknownItem is returned for an id outside the catalog.
var ErrUnknownItem = errors.New("unknown catalog item")

// ErrBadOption is returned for an option value outside the catalog.
var ErrBadOption = errors.New("invalid option value")

func pkg(id, label, group, desc, attr string) Item {
	return Item{ID: id, Label: label, Group: group, Description: desc, Kind: "package", hm: func(map[string]string) string { return "pkgs." + attr }}
}

var catalog = []Item{
	pkg("bun", "Bun", "runtimes", "JavaScript runtime and package manager", "bun"),
	pkg("deno", "Deno", "runtimes", "Secure TypeScript runtime", "deno"),
	{ID: "nodejs", Label: "Node.js", Group: "runtimes", Description: "Node.js with npm", Kind: "package",
		Options: []Option{{ID: "version", Values: []string{"20", "22", "24"}, Default: "24"}},
		hm:      func(o map[string]string) string { return "pkgs.nodejs_" + o["version"] }},
	{ID: "python", Label: "Python", Group: "runtimes", Description: "CPython with pip and venv", Kind: "package",
		Options: []Option{{ID: "version", Values: []string{"311", "312", "313"}, Default: "312"}},
		hm:      func(o map[string]string) string { return "pkgs.python" + o["version"] }},
	pkg("uv", "uv", "runtimes", "Fast Python package installer", "uv"),
	pkg("go", "Go", "runtimes", "The Go toolchain", "go"),
	pkg("rustup", "Rust", "runtimes", "rustup, cargo and rustc", "rustup"),
	pkg("ruby", "Ruby", "runtimes", "Ruby with bundler", "ruby"),
	pkg("elixir", "Elixir", "runtimes", "Elixir and Erlang/OTP", "elixir"),
	pkg("zig", "Zig", "runtimes", "The Zig toolchain", "zig"),
	pkg("postgresql-client", "PostgreSQL client", "databases", "psql and pg_dump for a remote database", "postgresql"),
	pkg("sqlite", "SQLite", "databases", "sqlite3 shell", "sqlite"),
	pkg("redis-cli", "Redis CLI", "databases", "redis-cli for a remote server", "redis"),
	pkg("chromium", "Chromium (headed)", "browsers", "A headed Chromium for the on-demand desktop", "chromium"),
	pkg("firefox", "Firefox", "browsers", "Firefox for the on-demand desktop", "firefox"),
	pkg("ffmpeg", "ffmpeg", "tools", "Audio and video conversion", "ffmpeg"),
	pkg("imagemagick", "ImageMagick", "tools", "Image conversion", "imagemagick"),
	pkg("awscli", "AWS CLI", "tools", "aws command", "awscli2"),
	pkg("azure-cli", "Azure CLI", "tools", "az command", "azure-cli"),
	pkg("kubectl", "kubectl", "tools", "Kubernetes client", "kubectl"),
	pkg("terraform", "OpenTofu", "tools", "tofu command", "opentofu"),
	pkg("htop", "htop", "tools", "Process viewer", "htop"),
	pkg("tree", "tree", "tools", "Directory listing", "tree"),
}

// Catalog returns the catalog in id order.
func Catalog() []Item {
	out := make([]Item, len(catalog))
	copy(out, catalog)
	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	return out
}

func find(id string) (Item, bool) {
	for _, it := range catalog {
		if it.ID == id {
			return it, true
		}
	}
	return Item{}, false
}

// Validate checks every id and option against the catalog.
func Validate(sel Selection) error {
	for _, s := range sel {
		it, ok := find(s.ID)
		if !ok {
			return fmt.Errorf("%w: %s", ErrUnknownItem, s.ID)
		}
		for name, val := range s.Options {
			var opt *Option
			for i := range it.Options {
				if it.Options[i].ID == name {
					opt = &it.Options[i]
				}
			}
			if opt == nil {
				return fmt.Errorf("%w: %s has no option %s", ErrBadOption, s.ID, name)
			}
			valid := false
			for _, v := range opt.Values {
				valid = valid || v == val
			}
			if !valid {
				return fmt.Errorf("%w: %s.%s=%s", ErrBadOption, s.ID, name, val)
			}
		}
	}
	return nil
}

// Render turns a selection into a home-manager fragment.
func Render(sel Selection) (string, error) {
	if err := Validate(sel); err != nil {
		return "", err
	}
	var pkgs []string
	seen := map[string]bool{}
	for _, s := range sel {
		if seen[s.ID] {
			continue
		}
		seen[s.ID] = true
		it, _ := find(s.ID)
		opts := map[string]string{}
		for _, o := range it.Options {
			opts[o.ID] = o.Default
		}
		for k, v := range s.Options {
			opts[k] = v
		}
		pkgs = append(pkgs, "    "+it.hm(opts))
	}
	var b strings.Builder
	b.WriteString(Header + "\n")
	b.WriteString("{ pkgs, ... }:\n{\n")
	b.WriteString("  home.packages = [\n")
	b.WriteString(strings.Join(pkgs, "\n"))
	if len(pkgs) > 0 {
		b.WriteString("\n")
	}
	b.WriteString("  ];\n}\n")
	return b.String(), nil
}

// IsGenerated reports whether a fragment came from Render.
func IsGenerated(fragment string) bool {
	return strings.HasPrefix(fragment, Header)
}
